version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: weather_mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: